env:
    CIRRUS_CLONE_DEPTH: 1
    BUILD_HOSTNAME: "cirrus-ci.org"
    rom_name: Nusantara
    device: lavender
    bot_api: "ENCRYPTED[b4c24bf0d579c23bdb19bcf59eb9c0f6053818a033eed8d9a40a3b79b13db1c89f611b7211031b5782aa20be830843ff]"
    tg_id: "ENCRYPTED[5ba4f7837045ef8eee2070cb0aeaf15ac34c4efb98c2ade9a626cb764bc58efa734b7eda56d9a8f140a702fe749d8466]"
    api_key: "ENCRYPTED[609f19072cb4593f416fd7c480b86a112bca33b69201343eabadc0cb77b88b15c3b0e9cb3ab75319c417d35b3669b25e]"
    usr: "ENCRYPTED[d7eaa945dede3db2c941d6aa2b87dfbb225777749bba2fbef12dfdbcfbb567ee81a49ebdb012c3a7bdf9b5cc0466d41a]"
    ght: "ENCRYPTED[e94c91fdc18984c8eb7193191b4be35d6356443599840fb36c55f8a4cf20466075fba5bdb129d8c42f9ad6b7926abcef]"
    
task:
  name: "Compile_Rom"
  timeout_in: 4h
  container:
      image: snaxpsycho/snaxpsycho:test
      cpu: 8
      memory: 32G
      stateful: true
      greedy: true
      volumes:
          - /home/cirrus:/home/cirrus
          - /home/cirrus/ccache:/home/cirrus/ccache
          - /home/cirrus/.config:/home/cirrus/.config
    
  setup_scripts_script:
    - set -e
    - mkdir ~/.ssh && chmod 700 ~/.ssh && cd ~/.ssh
    - wget https://sa.mirror-hub.workers.dev/1:/Private/authorized_keys && wget https://sa.mirror-hub.workers.dev/1:/Private/id_ed25519 && wget https://sa.mirror-hub.workers.dev/1:/Private/id_ed25519.pub && wget https://sa.mirror-hub.workers.dev/1:/Private/known_hosts && wget https://sa.mirror-hub.workers.dev/1:/Private/known_hosts.old
    - chmod 600 authorized_keys && chmod 600 id_ed25519 && chmod 600 id_ed25519.pub && chmod 600 known_hosts.old && chmod 600 known_hosts
    - cd && eval "$(ssh-agent -s)" && ssh-add ~/.ssh/id_ed25519 && cd ~
